# Generated by Django 3.0.8 on 2020-07-31 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_day', models.DateTimeField(blank=True, null=True)),
                ('return_day', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('book', models.ManyToManyField(related_name='book_order', to='webapp.Book', verbose_name='Book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_order', to=settings.AUTH_USER_MODEL, verbose_name='Order user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='Total books')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='webapp.Book', verbose_name='Book order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='webapp.Order', verbose_name='Order')),
            ],
        ),
        migrations.DeleteModel(
            name='BookOrder',
        ),
    ]
