# Generated by Django 3.0.8 on 2020-07-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200731_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='order',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='webapp.Category', verbose_name='Book Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderBook',
        ),
    ]
