# Generated by Django 3.0.8 on 2020-08-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200802_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='book',
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='webapp.Book', verbose_name='Book/s'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='webapp.Order', verbose_name='Order'),
        ),
    ]
