# Generated by Django 3.0.8 on 2020-08-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200807_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.OrderBook', verbose_name='Book'),
        ),
    ]
