# Generated by Django 3.0.8 on 2020-08-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_feedback_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
